#
#	CAN Utilities for CAN-over-Serial-Line Interfaces
#
#	Copyright (c) 2024  Uwe Vogt, UV Software, Berlin (info@uv-software.com)
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program   If not, see <https://www.gnu.org/licenses/>.
#
all:
	$(MAKE) -C can_test $@
	$(MAKE) -C can_moni $@

clean:
	$(MAKE) -C can_test $@
	$(MAKE) -C can_moni $@

pristine:
	$(MAKE) -C can_test $@
	$(MAKE) -C can_moni $@

install:
#	$(MAKE) -C can_test $@
#	$(MAKE) -C can_moni $@

